require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 130